export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export { default as Features } from './Features'
export { default as Savings } from './Savings'
export { default as Transfers } from './Transfers'
export { default as Loans } from './Loans'
export { default as Footer } from './Footer'
